// Report-only FULL-TEXT diff between wh11ed's hand-transcribed CORE RULES prose and wh40k-appdata's
// factions/_core-rules.json (generated by that repo's build-factions.mjs from the Core Rules
// publication). This is the one large data pillar that sync-appdata.mjs / sync-tracker.mjs
// never touched — the rulebook text in basicRules/battleRound/advancedRules/battlefields
// (sections 01-23) plus Core Abilities (24) via reference.js. Section 25 (Muster) is included
// too. Section 24's individual abilities and 25 have a different shape than the section-array
// files but are folded in below.
//
// Same architecture as sync-faction-text.mjs / sync-event-companion.mjs: strip wh11ed's
// enrichment layer (gloss tokens, cross-refs, bold) down to bare words on BOTH sides and print
// an actual word-level diff for every matched rule — NOT just a word-overlap ratio. The ratio
// (this script's previous version) was a triage signal only, and has been shown on both faction
// text and Event Companion to both under- and over-report drift (a generic-vocabulary section can
// score high overlap despite being entirely absent; a fully-present but reworded section can score
// low) — see APPDATA-SYNC-LESSONS.md #29. A real diff is strictly more informative and no slower
// to skim, since only genuinely differing text produces output at all.
//
// Usage:
//   node scripts/sync-core.mjs [numPrefix]   # e.g. "03" for just the Moving section
//   node scripts/sync-core.mjs               # all of 01-25
//
// Matching is by rule NUMBER (wh11ed `sectionNum` == appdata container subtitle / numbered
// accordion title, e.g. "03.01.02") — a far more stable key than the rule title, which both
// sides paraphrase. Report only; nothing is written.
import { pathToFileURL } from 'node:url'
import { loadAppdataCore, loadWh11edCore, appdataMarkup, plainText } from './lib/core-corpus.mjs'
import { APPDATA_EXCEPTIONS } from './lib/appdata-exceptions.mjs'

const REGISTERED = new Set(APPDATA_EXCEPTIONS.filter((e) => e.kind === 'core-rule-text').map((e) => e.num))

function wordDiff(whPlain, appPlain) {
  const a = whPlain.split(' ')
  const b = appPlain.split(' ')
  let lead = 0
  while (lead < a.length && lead < b.length && a[lead] === b[lead]) lead++
  let tail = 0
  while (tail < a.length - lead && tail < b.length - lead && a[a.length - 1 - tail] === b[b.length - 1 - tail]) tail++
  return { whMid: a.slice(lead, a.length - tail).join(' '), appMid: b.slice(lead, b.length - tail).join(' ') }
}
// What the two sides print differently without saying anything different (2026-10-03):
//   • our FAQ block under a rule (`### FAQs`, from tables/faq.json) — the app keeps FAQs apart;
//   • emphasis asterisks of any depth (`***D***'s` left "d s" behind) and pointer phrases ("see
//     below", "as described below") where the app writes the number;
//   • a word glued to the app's closing tag ("visible</b>or") — a space, not a new word.
const withoutFaqs = (t) => String(t || '').replace(/(^|\n)### FAQs?\b[\s\S]*?(?=\n### |$)/g, '')
const POINTERS = /\b(?:\(?see (?:below|above|left|right)\)?|as described (?:below|above))\b/g
const comparable = (t) => plainText(String(t || '').replace(/\*+/g, '')).replace(POINTERS, ' ').replace(/\s+/g, ' ').trim()
const unglue = (html) => String(html || '').replace(/<\/(b|i|u|em|strong|k)>(?=[A-Za-z])/g, '</$1> ')

function compare(out, label, whText, appText) {
  const wh = comparable(withoutFaqs(whText))
  const app = comparable(appText)
  if (!app && !wh) return
  if (wh === app) return
  if (!wh) {
    out.push(`  + ${label}: wh11ed has no text; appdata:\n      ${appText.replace(/\n/g, '\n      ')}`)
    return
  }
  if (!app) return // nothing on appdata's side to compare against — not our job here
  const { whMid, appMid } = wordDiff(wh, app)
  if (!whMid && !appMid) return
  out.push(`  ~ ${label}: text differs from appdata`)
  if (whMid && appMid) {
    out.push(`      wh11ed:  …${whMid}…`)
    out.push(`      appdata: …${appMid}…`)
  } else if (whMid) {
    out.push(`      wh11ed adds (not in appdata): …${whMid}…`)
  } else {
    out.push(`      appdata has (missing in wh11ed): …${appMid}…`)
  }
  out.push(`      canonical (paste-ready):\n        ${appText.replace(/\n/g, '\n        ')}`)
}

export async function run(argv = process.argv.slice(2)) {
const prefix = argv[0] || ''
const inScope = (num) => !prefix || num === prefix || num.startsWith(prefix + '.')

const wh = await loadWh11edCore()
const { app, dataVersion } = loadAppdataCore()

const appNums = [...app.keys()].filter(inScope).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
const whNums = [...wh.keys()].filter(inScope)

console.log(`sync-core — appdata data_version ${dataVersion}${prefix ? `, section ${prefix}` : ', sections 01-25'}`)
console.log(`  appdata numbered rules in scope: ${appNums.length}, wh11ed: ${whNums.length}\n`)

const lines = []
for (const num of appNums) {
  const a = app.get(num)
  const w = wh.get(num)
  // Two appdata container kinds aren't comparable prose here, so skip them (not wh11ed gaps):
  //  - `stratagem` containers (§15.02+ core stratagems) are already diffed by sync-tracker.mjs
  //    against _core-content.json.coreStratagems, and wh11ed renders them as StratCards, not
  //    numbered subsections.
  //  - `behaviourType` containers (move types: Normal/Advance/Fall-Back/Charge/Pile-In moves…)
  //    carry their rule text in appdata's `behaviour_type` table, which build-factions.mjs does
  //    not yet fold into _core-rules.json — until it does, they have no text to compare (TODO).
  if (a.type === 'stratagem' || !a.text) continue
  if (!w) {
    lines.push(`  + ${num} missing in wh11ed — appdata "${a.title}" (${a.section}):\n      ${appdataMarkup(a.text).replace(/\n/g, '\n      ')}`)
    continue
  }
  // A rule whose text follows an errata the app's own text has not taken in is the registry's
  // to watch (scripts/lib/appdata-exceptions.mjs, kind core-rule-text) — not this report's.
  if (REGISTERED.has(num)) continue
  compare(lines, `${num} "${w.title}" [${w.file}] (appdata "${a.title}")`, w.body, appdataMarkup(unglue(a.text)))
}
for (const num of whNums.sort((x, y) => x.localeCompare(y, undefined, { numeric: true }))) {
  if (!app.has(num)) lines.push(`  - ${num} "${wh.get(num).title}" [${wh.get(num).file}] not in appdata (wh11ed-only subsection)`)
}

if (!lines.length) console.log('  no text differences found')
else console.log(lines.join('\n'))
console.log(`\n  ${lines.length} finding(s).`)
return 0
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
// `process.exit()` would truncate a report this long — stdout writes to a pipe are async, and
// exiting drops whatever is still buffered (the tail of the run vanished when piping to `head`).
// Set the code and let the process end on its own.
if (isMain) process.exitCode = await run()
